// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oiawdxbwnfupwajxfdcp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9pYXdkeGJ3bmZ1cHdhanhmZGNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYzMjc0MzMsImV4cCI6MjA4MTkwMzQzM30.1e8SkUBYhRpt1XpR9EeBKytaX0eFXNH33aD1em_mcnk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});